### ISSUE TITLE
First and last YAxis labels are changed to numbers

### ISSUE THREAD

**Issue by schutze** [laff/technical-indicators#21]
This plugin changes the first and last YAxis labels to numbers, 0 for the first data point and another number for the last.  It should not change the existing series data, just add a new series for the trend data.

**Comment by TorsteinHonsi** [comment]
Thanks for reporting, but technical indicators are now part of the Highstock core product, and this project is not actively maintained. See https://www.highcharts.com/docs/chart-and-series-types/technical-indicator-series .

**Comment by schutze** [comment]
Nice that indicators are now part of the Highstock core but:
- Can they be used with Highcharts?
- Are they supported by the Highcharts .NET wrapper?
- What about linear regression analysis?  I don't see it listed on the Technical Indicator Series page.

**Comment by pawelfus** [comment]
Hi!

- Yes, technical indicators module works with Highcharts, but it is still part of the Highstock product
- Yes, .NET wrapper has been released with support for new series types and technical indicators
- Linear regression is not supported, but we can simply add this indicator type: http://jsfiddle.net/fczj7av6/
