### ISSUE TITLE
trendline data is empty

### ISSUE THREAD

**Issue by valugi** [laff/technical-indicators#3]
If a serie is set an id at a later date, even if the chart is redrawn, the trendline serie is added but with empty data. Here is an example that works: http://jsfiddle.net/g9ymtkw3/2/ and one that doesnt : http://jsfiddle.net/g9ymtkw3/3/

**Comment by arnabk** [comment]
The way you are assigning ID is wrong. You have to call update method of series object.
```xml
chart.series[0].update({id : 'primary'});
```

See it live http://jsfiddle.net/arnabk/nkukrzyy/1/

**Comment by valugi** [comment]
ok. thanks

**Comment by lkwg82** [comment]
@valugi close the issue, if it is solved. This helps future visitors.
