### ISSUE TITLE
Can be used with highstock 2.0 ?

### ISSUE THREAD

**Issue by nitinsurana** [laff/technical-indicators#4]
I am using high-stock 2.0.4 in my project. Is this project in development ? Has it been tested for highstock 2.0 ?

**Comment by laff** [comment]
Sorry for answering this late. 
The plugin has not been tested nor developed since late 2013, which was before highstock 2.0.

I think blacklabel has a better updated similar plugin here: https://github.com/blacklabel/indicators/
